# Generated by Django 3.0.5 on 2020-05-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200430_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='Blog_image/blog.jpg', null=True, upload_to='Blog_image/%Y/%m/%d'),
        ),
    ]
